CodeWars::Kata
Dictionary<string, string> CodeWars.Kata._soundDict
Referenced by CodeWars.Kata.SoundexSingle.
string CodeWars.Kata._codeString
Кодовая строка
Referenced by CodeWars.Kata.ToBase64.
static List<long[]> CodeWars.Kata.RemovNb(long n)
Возвращает два числа из натурального ряда, произведение которых равно сумме всех чисел этого ряда, исключая эти два числа
n Верхний предел ряда. Всегда > 0 Массив чисел
static BigInteger CodeWars.Kata.Perimeter(BigInteger n)
Возвращает сумму периметров квадратов в ряду Фибоначи
n
static bool CodeWars.Kata.IsMerge(string s, string part1, string part2)
Возвращает возможность объединения и перемешиваения двух строку в третию, без изменения порядка символов в исходных строках.
s Итоговая строка part1 Первая строка part2 Вторая строка true, если объединение возможно
References CodeWars.Kata.MayExtract.
static string CodeWars.Kata.Interpret(string code, int iterations, int width, int height)
Интерпретатор
code Код Paintfuck, который должен быть выполнен, передается как строка. iterations width height
static string CodeWars.Kata.Soundex(string names)
Преобразует слова английского языка по алгоритму SOUNDEX
names Строка из слов, разделённых пробелом SOUNDEX-коды группы слов
References CodeWars.Kata.SoundexSingle.
Referenced by CodeWars.Tests.KataTests.SoundexTest.
static string CodeWars.Kata.ToBase64(string s)
Возвращает результат base64 кодирования исходной строки s с использованием UTF-8
s Исходная строка Результат
References CodeWars.Kata._codeString, CodeWars.Kata.BitGroups.
static string CodeWars.Kata.FromBase64(string s)
Возвращает результат base64 декодирования исходной последовательности s с использованием UTF-8
s Исходная последовательность Результат
References CodeWars.Kata.BitGroups.
static string CodeWars.Kata.BundesLigaTable(params string[] results)
References CodeWars.Kata.Kommando.GoalsOut, CodeWars.Kata.Kommando.MatchCount, CodeWars.Kata.Kommando.Points, CodeWars.Kata.Kommando.SameResult, CodeWars.Kata.Kommando.Ties.
Referenced by CodeWars.Tests.KataTests.BundesLigaTableTest.
static string CodeWars.Kata.ListSquared(long[] a)
m Меньшее число диапазона n Большее число диапазона
Referenced by CodeWars.Tests.KataTests.ListSquaredTest.
static List<long> CodeWars.Kata.GetDividers(long dvsn)
References CodeWars.Kata.SimpeDividers.
Referenced by CodeWars.Tests.KataTests.GetDividersTest.
static int CodeWars.Kata.Persistence(long n)
Возвращает количество операций умножения, которые нужно провести над цифрами данного числа до тех пор, пока они не станут одной цифрой.
n Проверяемое число Необходимое число умножений
static String CodeWars.Kata.LongestConsec(string[] strarr, int k)
Вернуть первую наидлиннейшую строку, состоящую из k элементов массива
strarr Входящий массив k Нужное число элементов Строка
static long [] CodeWars.Kata.SumDigPow(long a, long b)
Возвращает массив чисел из входящего диапазона с такими свойствами, что эти числа равны сумме составляющих их цифр, в степенях, равных местам цифр в числе. (например: 135 = 1^1 + 3^2 + 5^3)
a Начало входящего диапазона b Конец входящего диапазона Массив чисел, удовлетворяющих условию
static string CodeWars.Kata.Order(string words)
Возвращает строку из слов исходной строки, отсортированных согласно числам в этих словах
words Исходная строка Итоговая строка
static int CodeWars.Kata.Solution(int value)
Возвращает сумму всех чисел в натуральном ряду, которые делятся на 3 или на 5
value Верхний предел ряда Сумма
static long CodeWars.Kata.FindNb(params long[] m)
Возвращает количество кубов, нужное для достижения объёма = m.Кубы начинаются с размеров 1х1х1.Сторона каждого последующего куба больше стороны предыдущего на 1. m Нужный объём Количество кубов или -1, если объём не может уместить количество.
static string CodeWars.Kata.HighAndLow(string numbers)
7 Возвращает самое большое и самое малое числа из строки чисел
numbers Строка чисел, разделённых пробелами Строка из наибольшего и наименьшего чисел
static string CodeWars.Kata.Maskify(string cc)
Маскирует символом # все символы входящей строки, кроме последних четырёх
cc Строка,которую следует замаскировать Замаскированная строка
static bool CodeWars.Kata.IsIsogram(string s)
Указывает является ли проверяемая строка изограммой
s Проверяемая строка true если является
static int CodeWars.Kata.SquareDigits(int n)
Возвращает число, состоящие из квадратов каждой цифры исходного числа
n Исходное число Число из квадратов
static int CodeWars.Kata.NbYear(int p0, double percent, int aug, int p)
Возвращает количество периодов, за которое начальное количество достигнет целевого
p0 Начальное количество percent Периодическое изменение в процентах aug Периодическое абсолютное изменение p Целевое количество Количество периодов
static IEnumerable<string> CodeWars.Kata.FriendOrFoe(string[] n)
Возвращает строки, длина которых = 4
n Массив строк для проверки Коллекция строк
static long CodeWars.Kata.RowSumOddNumbers(long n)
Возвращает сумму нечётных чисел числового треугольника
n Номер блока, считая от 1 Сумма нечётных чисел
static int [] CodeWars.Kata.MinMax(int[] lst)
static bool CodeWars.Kata.MayExtract(string s, params string[] parts)
Referenced by CodeWars.Kata.IsMerge.
static string CodeWars.Kata.SoundexSingle(string word)
References CodeWars.Kata._soundDict.
Referenced by CodeWars.Kata.Soundex.
static List<string> CodeWars.Kata.BitGroups(string s, int oldSize, int newSize)
Referenced by CodeWars.Kata.FromBase64, CodeWars.Kata.ToBase64.
static IEnumerable<long> CodeWars.Kata.SimpeDividers(long dvsn)
Referenced by CodeWars.Kata.GetDividers.